### ISSUE TITLE
[keyboard_file] Three is no image in the rviz.

### ISSUE THREAD

**Issue by yileichen123** [Durant35/kitti_ros#26]
I had download the kitti data and I had all the requirements.But there is no images and points on the screen. And there is no error.It just show and pause as the following:
[ 2011-09-26 13:04:32.335337 ] # of Point Clouds: 493588
###########
[INFO] Show image:  0000000000.png

And the url: ROS_MASTER_URI=http://localhost:11311, I can't cotact on the website

**Comment by maxwellfrom** [comment]
I met the same problem, help! @Durant35 Thanks!

**Comment by maxwellfrom** [comment]
Have you solved the problem? @yileichen123

**Comment by Durant35** [comment]
Have you try?
> ![image](https://user-images.githubusercontent.com/6770853/51068660-54fa4180-165c-11e9-9c7e-3db9f4135262.png)

**Comment by maxwellfrom** [comment]
yes, I have tried that.

**Comment by Durant35** [comment]
I have just followed the README, and everything goes well.
![image](https://user-images.githubusercontent.com/6770853/51082722-05913f80-1748-11e9-9c8e-8bb8a1f867f2.png)

**Comment by maxwellfrom** [comment]
I tried your latest version, and it was same as before.

**Comment by maxwellfrom** [comment]
When I use the keyboard to control, is there anything needs to be noticed?

**Comment by Durant35** [comment]
@maxwellfrom @yileichen123 I think the only problem is the keyboard callback function couldn't be triggered, and the error information will be shown on your terminal, supported by ROS's roslaunch.

If you use any IDE, like VS code above, I'm afraid that I can't help more, sorry.

**Comment by Durant35** [comment]
Move to LidarPerception/kitti_ros_tmp#4
