### ISSUE TITLE
ImportError: No module named evdev

### ISSUE THREAD

**Issue by Durant35** [Durant35/kitti_ros#28]
> process[kitti_player-1]: started with pid [10175]
Traceback (most recent call last):
  File "/home/gary/Workspace/intern_ws/lidar_perception_ws/src/kitti_ros/scripts/kitti_player.py", line 34, in <module>
    from evdev import InputDevice
ImportError: No module named evdev

**Comment by JYS997760473** [comment]
May I ask which python and pip version is?

**Comment by Durant35** [comment]
python3.x is ok, I think. Here I used python3.5 and releated pip3

**Comment by JYS997760473** [comment]
Thanks. It works now.
________________________________
